on:
  push:
    branches:
    - main

# jobs are the task which will run whenever there is a change
jobs:
  e2e-tests:
    runs-on: macos-latest # or ubuntu-latest, windows-latest
    #strategy:
    #  fail-fast: true

    steps:
    # download all the code to the actions-maschine
      - name: Get Code
        uses: actions/checkout@v3

    # setup the version from pacakage.json
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14

    # install all the dependencies from pasckage.json
      - name: Install dependencies
        run: npm ci  # npm ci will install only the depenencies in project

    # install playwright
      - name: Install playwright
        run: npx playwright install --with-deps
      
    # run the tests
      - name: run tests
        run: npm run testCucumber2
        # continue-on-error: false

      - name: Check if test failed
        if: always()
        run: |
          if [ $? -ne 0 ]
          then
            echo "Tests failed"
            --exit
          fi
      
      - name: Archieve Cucumber Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Report
          path: Reports/
          retention-days: 5